{{- if eq .Values.agent.version "v2" }}
apiVersion: v1
kind: Secret
metadata:
  name: agent-config
  namespace: {{ include "opni-agent.namespace" . }}
  labels:
    {{- include "opni-agent.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    apiVersion: v1beta1
    kind: AgentConfig
    spec:
      gatewayAddress: {{ include "opni-agent.gatewayAddress" . }}
      identityProvider: kubernetes
      listenAddress: :8080
      trustStrategy: pkp
      storage:
        type: customResources
      plugins:
        dir: /var/lib/opni-agent/plugins
      bootstrap:
        {{- if .Values.bootstrapInCluster.enabled }}
        inClusterManagementAddress: {{ .Values.bootstrapInCluster.managementAddress }}
        {{- else }}
        token: {{ .Values.token }}
        pins: [{{ .Values.pin }}]
        {{- end }}
      {{- if .Values.logLevel }}
      logLevel: {{ .Values.logLevel }}
      {{- end }}
      {{- if .Values.profiling }}
      profiling: {{ .Values.profiling }}
      {{- end }}
{{- end }}