apiVersion: apps/v1
kind: Deployment
metadata:
  name: nulog-inference-service-control-plane
  namespace: opni-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nulog-inference-service-control-plane
  template:
    metadata:
      labels:
        app: nulog-inference-service-control-plane
    spec:
      containers:
      - name: nulog-inference-service-control-plane
        image: tybalex/nulog-inference-service:v0.1
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:%NATS_PASSWORD%@nats-client.opni-system.svc:4222"
        - name: ES_ENDPOINT
          value: "https://opendistro-es-client-service.opni-system.svc.cluster.local:9200"
        - name: MINIO_ENDPOINT
          value: "http://minio.opni-system.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "%MINIO_ACCESS_KEY%"
        - name: MINIO_SECRET_KEY
          value: "%MINIO_SECRET_KEY%"
        - name: MODEL_THRESHOLD
          value: "0.6"
        - name: MIN_LOG_TOKENS
          value: "4"
        - name: IS_CONTROL_PLANE_SERVICE
          value: "True"
        resources:
          limits:
            memory: 2Gi
            cpu: "7.5"
          requests:
            memory: 1Gi
            cpu: "1"