lint = true
test = true

[charts.git]
	repo = "github.com/rancher/opni"
	branch = "charts-repo"
[charts.git.auth]
	email = "rancherbot@rancher.com"
	username = "Rancher Bot"

[charts.oci]
	repo = "docker.io"

[images.opni]
	repo = "docker.io/rancher/opni"

[images.minimal]
	repo = "docker.io/rancher/opni"
	tag-suffix = "-minimal"

[images.opensearch.build]
	dashboards-version = "2.8.0"
	opensearch-version = "2.8.0"
	plugin-version = "0.11.0-rc3"

[images.opensearch.dashboards]
	repo = "docker.io/rancher/opensearch-dashboards"
	tag-suffix = "-2.8.0"

[images.opensearch.opensearch]
	repo = "docker.io/rancher/opensearch"
	tag-suffix = "-2.8.0"

[images.opensearch.update-service]
	repo = "docker.io/rancher/opni-opensearch-update-service"

[images.python-base]
	repo = "docker.io/rancher/opni-python-base"
	tag = "3.9"

[images.python-torch]
	repo = "docker.io/rancher/opni-python-base"
	tag = "3.9"
	tag-suffix = "-torch"
