{{- if .Values.ai.enabled }}
apiVersion: opni.io/v1beta2
kind: OpniCluster
metadata:
  name: opni
  namespace: {{ include "opni.namespace" . }}
spec:
  version: v{{ .Chart.AppVersion }}
  deployLogCollector: false
  services:
    payloadReceiver:
      enabled: false
    gpuController:
      enabled: false
    inference:
      enabled: true
      pretrainedModels:
      - name: control-plane
    metrics:
      enabled: {{ .Values.monitoring.enabled }}
      prometheusEndpoint: https://cortex-query-frontend:8080
      extraVolumeMounts:
      - name: cortex-client-certs
        mountPath: /run/cortex/certs/client
        secret:
          secretName: cortex-client-cert-keys
          defaultMode: 256
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt
      - name: cortex-server-cacert
        mountPath: /run/cortex/certs/server
        secret:
          secretName: cortex-serving-cert-keys
          defaultMode: 256
          items:
            - key: ca.crt
              path: ca.crt
  opensearch:
    externalOpensearch:
      name: opni
      namespace: {{ include "opni.namespace" . }}
    enableLogIndexManagement: false
    enableIngestPreprocessing: true
{{- with .Values.ai.s3 }}
  s3:
    {{- toYaml . | nindent 4 }}
{{- end }}
  nats:
    authMethod: nkey
{{- end }}