
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: opnidemoes.demo.opni.io
spec:
  group: demo.opni.io
  names:
    kind: OpniDemo
    listKind: OpniDemoList
    plural: opnidemoes
    singular: opnidemo
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OpniDemo is the Schema for the opnidemoes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpniDemoSpec defines the desired state of OpniDemo
            properties:
              components:
                properties:
                  infra:
                    properties:
                      helmController:
                        type: boolean
                      localPathProvisioner:
                        type: boolean
                    type: object
                  opni:
                    properties:
                      elastic:
                        type: boolean
                      minio:
                        type: boolean
                      nats:
                        type: boolean
                      rancherLogging:
                        type: boolean
                      traefik:
                        type: boolean
                    type: object
                required:
                - infra
                - opni
                type: object
              elasticsearchPassword:
                type: string
              elasticsearchUser:
                type: string
              minioAccessKey:
                type: string
              minioSecretKey:
                type: string
              minioVersion:
                type: string
              natsMaxPayload:
                type: integer
              natsPassword:
                type: string
              natsReplicas:
                type: integer
              natsVersion:
                type: string
              nulogServiceCpuRequest:
                type: string
              nvidiaVersion:
                type: string
              quickstart:
                type: boolean
              traefikVersion:
                type: string
            required:
            - components
            - elasticsearchPassword
            - elasticsearchUser
            - minioAccessKey
            - minioSecretKey
            - minioVersion
            - natsMaxPayload
            - natsPassword
            - natsReplicas
            - natsVersion
            - nulogServiceCpuRequest
            - nvidiaVersion
            - quickstart
            - traefikVersion
            type: object
          status:
            description: OpniDemoStatus defines the observed state of OpniDemo
            properties:
              conditions:
                items:
                  type: string
                type: array
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
