---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: collectorconfigs.logging.opni.io
spec:
  group: logging.opni.io
  names:
    kind: CollectorConfig
    listKind: CollectorConfigList
    plural: collectorconfigs
    singular: collectorconfig
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              aks:
                type: object
              eks:
                type: object
              gke:
                type: object
              k3s:
                properties:
                  containerEngine:
                    type: string
                  logPath:
                    type: string
                type: object
              kubeAuditLogs:
                properties:
                  enabled:
                    type: boolean
                  logPath:
                    type: string
                type: object
              provider:
                enum:
                - aks
                - eks
                - gke
                - k3s
                - rke
                - rke2
                - generic
                type: string
              rke:
                properties:
                  logLevel:
                    type: string
                type: object
              rke2:
                properties:
                  logPath:
                    type: string
                type: object
              seLinuxEnabled:
                type: boolean
              selector:
                properties:
                  exclude:
                    items:
                      properties:
                        namespace:
                          type: string
                        podNames:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  include:
                    items:
                      properties:
                        namespace:
                          type: string
                        podNames:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                type: object
            required:
            - provider
            type: object
          status:
            properties:
              conditions:
                items:
                  type: string
                type: array
              message:
                type: string
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
